### ISSUE TITLE
Lua or C?

### ISSUE THREAD

**Issue by deanturpin** [deanturpin/writing-a-wireshark-dissector-#1]
@fnxweb @hisdeedsaredust @JonnyKelso

"Dissectors are usually written in C, it's also possible to write them in Lua for fast prototyping."

So it's still not a trivial thing. Might be quicker to bash it out in Lua but I suspect it's going to take more than one train journey.

**Comment by fnxweb** [comment]
I anticipated writing a C++ dissector that linked to Messages (or dynamic load a given one) and could use that to properly dig into any message.

Might need a Pip engine to walk the binary. Not looked for years.

On 3 May 2017 18:32:12 BST, Dean Turpin <notifications@github.com> wrote:
>@fnxweb @hisdeedsaredust @JonnyKelso
>
>"Dissectors are usually written in C, it's also possible to write them
>in Lua for fast prototyping."
>
>So it's still not a trivial thing. Might be quicker to bash it out in
>Lua but I suspect it's going to take more than one train journey.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/deanturpin/writing-a-wireshark-dissector-/issues/1

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by deanturpin** [comment]
Tomorrow never comes
